name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Docker Hub Login 
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Check Docker login
        run: docker info

      - name: Docker Build Setup
        uses: docker/setup-buildx-action@v3

      - name: Build and test backend
        uses: docker/build-push-action@v6
        with:
          target: test
          load: true
          file: ./backend/Dockerfile
          
      - name: Build and test frontend
        uses: docker/build-push-action@v6
        with:
          target: test
          load: true
          file: ./frontend/Dockerfile

      - name: Build and push backend
        uses: docker/build-push-action@v6
        with:
          file: ./backend/Dockerfile
          platforms: linux/amd64
          push: true
          target: final
          tags: ${{ secrets.DOCKER_USERNAME }}/jumpiteasy-web-backend:latest

      - name: Build and push frontend
        uses: docker/build-push-action@v6
        with:
          file: ./frontend/Dockerfile
          platforms: linux/amd64
          push: true
          target: final
          tags: ${{ secrets.DOCKER_USERNAME }}/jumpiteasy-web-frontend:latest
