name: CI

on:
  push:
    branches:
      - main

jobs:
  lint-backend:
    name: Lint Backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Docker Build Lint Backend
        uses: docker/build-push-action@v6
        with:
          target: lint
          load: true
          file: ./backend/Dockerfile

  lint-frontend:
    name: Lint Frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Docker Build Lint Frontend
        uses: docker/build-push-action@v6
        with:
          target: lint
          load: true
          file: ./frontend/Dockerfile

  test-backend:
    name: Test Backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Docker Build Test Backend
        uses: docker/build-push-action@v6
        with:
          target: test
          load: true
          file: ./backend/Dockerfile

  test-frontend:
    name: Test Frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Docker Build Test Frontend
        uses: docker/build-push-action@v6
        with:
          target: test
          load: true
          file: ./frontend/Dockerfile

  build-and-push:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest
    needs: [lint-backend, lint-frontend, test-backend, test-frontend]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Docker Hub Login 
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Backend Image
        uses: docker/build-push-action@v6
        with:
          file: ./backend/Dockerfile
          platforms: linux/amd64
          push: true
          target: final
          tags: ${{ secrets.DOCKER_USERNAME }}/jumpiteasy-web-backend:latest

      - name: Build and Push Frontend Image
        uses: docker/build-push-action@v6
        with:
          file: ./frontend/Dockerfile
          platforms: linux/amd64
          push: true
          target: final
          tags: ${{ secrets.DOCKER_USERNAME }}/jumpiteasy-web-frontend:latest
